name: Elliot Bentley
title: 'Elliot Bentley'
url: https://ejb.github.io
description: 'brief notes & experiments by @elliot bentley'
highlighter: rouge
baseurl: ''
markdown: kramdown
kramdown:
  input: GFM
plugins:
- jekyll-redirect-from
